# -*- coding: utf-8 -*-
"""UtilityFunction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FYabDjLfDUWVpGYX5ptJKZc9iYX7Rpjb
"""

import matplotlib.pyplot as plt
import numpy as np

# helper function for data visualization
def visualize(image, mask):
  image_number = random.randint(0, len(im. age))
  plt.figure(figsize=(12, 6))
  plt.subplot(121)
  plt.imshow(np.reshape(image[image_number], (256, 256)), cmap='gray')
  plt.subplot(122)
  plt.imshow(np.reshape(mask[image_number], (256, 256)), cmap='gray')
  plt.show()

# helper function for data visualization
def denormalize(x):
    """Scale image to range 0..1 for correct plot"""
    x_max = np.percentile(x, 98)
    x_min = np.percentile(x, 2)
    x = (x - x_min) / (x_max - x_min)
    x = x.clip(0, 1)
    return x